apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: broker-service-pv-claim
  labels:
    app: broker
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: broker
spec:
  selector:
    app: broker
  ports:
    - protocol: TCP
      port: 9092
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: broker-nodeport
spec:
  selector:
    app: broker
  ports:
    - protocol: TCP
      port: 9092
      targetPort: 9092
  type: NodePort
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: broker
spec:
  selector:
    matchLabels:
      app: broker
  serviceName: broker
  replicas: 1 
  template:
    metadata:
      name: broker-pod
      labels:
        app: broker
    spec:
      containers:
      - name: broker
        image: confluentinc/cp-kafka:6.0.11
        env:
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "zookeper:2181"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "PLAINTEXT://broker:9092"
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"          
        ports:
        - containerPort: 9092
          name: broker
        volumeMounts:
        - name: broker-service-persistent-storage
          mountPath: /var/lib/kafka/data
        imagePullPolicy: Never
      volumes:
       - name: broker-service-persistent-storage
         persistentVolumeClaim:
          claimName: broker-service-pv-claim