apiVersion: v1
kind: Namespace
metadata:
  name: development
---
apiVersion: v1
kind: Service
metadata:
  name: config-server
  namespace: development
  labels:
    app: config-server
spec:
  selector:
    app: config-server
  ports:
    - protocol: TCP
      port: 8888
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: config-server-nodeport
  namespace: development
  labels:
    app: config-server
spec:
  selector:
    app: config-server
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
  namespace: development
spec:
  selector:
    matchLabels:
      app: config-server
  strategy:
    type: Recreate
  template:
    metadata:
      name: config-server-pod
      labels:
        app: config-server
    spec:
      containers:
      - name: config-server
        image: kamposdiego/config-server:1.0.0
        ports:
        - containerPort: 8888
          name: config-server
        imagePullPolicy: Never
