apiVersion: v1
kind: Namespace
metadata:
  name: development
---
apiVersion: v1
kind: Service
metadata:
  name: location-document-service
  namespace: development  
  labels:
    app: location-document
spec:
  selector:
    app: location-document
  ports:
    - protocol: TCP
      port: 8182
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: location-document-nodeport
  namespace: development  
spec:
  selector:
    app: location-document
  ports:
    - protocol: TCP
      port: 8182
      targetPort: 8182
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: location-document
  namespace: development  
spec:
  selector:
    matchLabels:
      app: location-document
  strategy:
    type: Recreate
  template:
    metadata:
      name: location-document-pod
      labels:
        app: location-document
    spec:
      containers:
      - name: location-app
        image: kamposdiego/location-document:1.0.0
        ports:
        - containerPort: 8182
          name: location-mongo
        imagePullPolicy: Never
