apiVersion: v1
kind: Service
metadata:
  name: location-document-service
  labels:
    app: location-document
spec:
  selector:
    app: location-document
  ports:
    - protocol: TCP
      port: 8182
  clusterIP: None