apiVersion: v1
kind: Service
metadata:
  name: location-app-service
  labels:
    app: location-app
spec:
  selector:
    app: location-app
  ports:
    - protocol: TCP
      port: 8180
  clusterIP: None