apiVersion: v1
kind: Service
metadata:
  name: location-document-nodeport
spec:
  selector:
    app: location-document
  ports:
    - protocol: TCP
      port: 8182
      targetPort: 8182
  type: NodePort
