apiVersion: v1
kind: Service
metadata:
  name: location-cache-service
  labels:
    app: location-cache
spec:
  selector:
    app: location-cache
  ports:
    - protocol: TCP
      port: 8181
  clusterIP: None