apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-service-pv-claim
  labels:
    app: mongo-service
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
