apiVersion: v1
kind: Service
metadata:
  name: mongo-service-nodeport
spec:
  selector:
    app: mongo-service
  ports:
    - protocol: "TCP"
      port: 27017
      targetPort: 27017
  type: NodePort
