apiVersion: v1
kind: Namespace
metadata:
  name: development
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-service-pv-claim
  namespace: development
  labels:
    app: mongo-service
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  namespace: development
spec:
  selector:
    app: mongo-service
  ports:
    - protocol: TCP
      port: 27017
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service-nodeport
  namespace: development
spec:
  selector:
    app: mongo-service
  ports:
    - protocol: "TCP"
      port: 27017
      targetPort: 27017
  type: NodePort
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-service
  namespace: development
spec:
  selector:
    matchLabels:
      app: mongo-service
  serviceName: mongo-service
  replicas: 1
  template:
    metadata:
      name: mongo-service-pod
      labels:
        app: mongo-service
    spec:
      containers:
      - name: mongo-service
        image: mongo:5.0.5
        ports:
        - containerPort: 27017
          name: mongo
        volumeMounts:
        - name: mongo-service-persistent-storage
          mountPath: /data/db
        imagePullPolicy: Never
      volumes:
       - name: mongo-service-persistent-storage
         persistentVolumeClaim:
          claimName: mongo-service-pv-claim