apiVersion: v1
kind: Namespace
metadata:
  name: development
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: neo4j-service-pv-claim
  namespace: development
  labels:
    app: neo4j-service
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: neo4j-service
  namespace: development  
spec:
  selector:
    app: neo4j-service
  ports:
    - protocol: TCP
      port: 7474
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: neo4j-service-nodeport
  namespace: development
spec:
  selector:
    app: neo4j-service
  ports:
    - protocol: TCP
      port: 7474
      targetPort: 7474
      name: neo4j-admin
    - protocol: TCP
      port: 7687
      targetPort: 7687
      name: neo4j-service
  type: NodePort
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: neo4j-service
  namespace: development
spec:
  selector:
    matchLabels:
      app: neo4j-service
  serviceName: neo4j-service
  replicas: 1
  template:
    metadata:
      name: neo4j-service-pod
      labels:
        app: neo4j-service
    spec:
      containers:
      - name: neo4j-service
        image: neo4j:4.4.2-community
        env:
        - name: NEO4J_AUTH
          value: neo4j/neo4JPasswd
        ports:
        - containerPort: 7474
          name: neo4j-admin
        - containerPort: 7687
          name: neo4j-service          
        volumeMounts:
        - name: neo4j-service-persistent-storage
          mountPath: /data
        imagePullPolicy: Never
      volumes:
       - name: neo4j-service-persistent-storage
         persistentVolumeClaim:
          claimName: neo4j-service-pv-claim