apiVersion: apps/v1
kind: Deployment
metadata:
  name: neo4j-service
spec:
  selector:
    matchLabels:
      app: neo4j-service
  strategy:
    type: Recreate
  template:
    metadata:
      name: neo4j-service-pod
      labels:
        app: neo4j-service
    spec:
      containers:
      - name: neo4j-service
        image: neo4j:4.4.2-community
        env:
        - name: NEO4J_AUTH
          value: neo4j/neo4JPasswd
        ports:
        - containerPort: 7474
          name: neo4j-admin
        - containerPort: 7687
          name: neo4j-service          
        volumeMounts:
        - name: neo4j-service-persistent-storage
          mountPath: /data
        imagePullPolicy: Never
      volumes:
        - name: neo4j-service-persistent-storage
          persistentVolumeClaim:
            claimName: neo4j-service-pv-claim