apiVersion: v1
kind: Service
metadata:
  name: neo4j-service-nodeport
spec:
  selector:
    app: neo4j-service
  ports:
    - protocol: TCP
      port: 7474
      targetPort: 7474
      name: neo4j-admin
    - protocol: TCP
      port: 7687
      targetPort: 7687
      name: neo4j-service
  type: NodePort
