apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: neo4j-service-pv-claim
  labels:
    app: neo4j-service
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
