apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-service-pv-claim
  labels:
    app: postgresql-service
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
