apiVersion: v1
kind: Service
metadata:
  name: postgresql-service-nodeport
spec:
  selector:
    app: postgresql-service
  ports:
    - protocol: "TCP"
      port: 5432
      targetPort: 5432
  type: NodePort
