apiVersion: v1
kind: Namespace
metadata:
  name: development
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbit-data-pv-claim
  namespace: development  
  labels:
    app: rabbitmq-service
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  namespace: development  
spec:
  selector:
    app: rabbitmq-service
  ports:
    - protocol: TCP
      port: 5672
      name: rabbitmq-service      
    - protocol: TCP
      port: 15672
      name: rabbitmq-admin            
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service-nodeport
  namespace: development  
spec:
  selector:
    app: rabbitmq-service
  ports:
    - protocol: "TCP"
      port: 5672
      name: rabbitmq-service
      targetPort: 5672
    - protocol: "TCP"
      port: 15672
      targetPort: 15672
      name: rabbitmq-admin
  type: NodePort
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq-service
  namespace: development  
spec:
  selector:
    matchLabels:
      app: rabbitmq-service
  serviceName: rabbitmq-service
  replicas: 1
  template:
    metadata:
      name: rabbitmq-service-pod
      labels:
        app: rabbitmq-service
    spec:
      containers:
      - name: rabbitmq-service
        image: rabbitmq:3.9-management-alpine
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: rabbitmq
        - name: RABBITMQ_DEFAULT_PASS
          value: rabbitmqpasswd
        ports:
        - containerPort: 5672
          name: rabbitmq
        - containerPort: 15672
          name: rabbitmq-admin
        volumeMounts:
        - name: rabbit-data-persistent-storage
          mountPath: /var/lib/rabbitmq/mnesia/rabbit@my-rabbit
        imagePullPolicy: Never
      volumes:
       - name: rabbit-data-persistent-storage
         persistentVolumeClaim:
          claimName: rabbit-data-pv-claim