apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-service-pv-claim
  labels:
    app: redis-service
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
