apiVersion: v1
kind: Namespace
metadata:
  name: development
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-service-pv-claim
  namespace: development  
  labels:
    app: redis-service
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: development  
spec:
  selector:
    app: redis-service
  ports:
    - protocol: TCP
      port: 6379
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service-nodeport
  namespace: development  
spec:
  selector:
    app: redis-service
  ports:
    - protocol: "TCP"
      port: 6379
      targetPort: 6379
  type: NodePort
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-service
  namespace: development  
spec:
  selector:
    matchLabels:
      app: redis-service
  serviceName: redis-service
  replicas: 1
  template:
    metadata:
      name: redis-service-pod
      labels:
        app: redis-service
    spec:
      containers:
      - name: redis-service
        image: redis:6.2.6-bullseye
        command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]
        ports:
        - containerPort: 6379
          name: redis
        volumeMounts:
        - name: redis-service-persistent-storage
          mountPath: /data
        imagePullPolicy: Never
      volumes:
       - name: redis-service-persistent-storage
         persistentVolumeClaim:
          claimName: redis-service-pv-claim