apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeper
spec:
  selector:
    matchLabels:
      app: zookeper
  strategy:
    type: Recreate
  template:
    metadata:
      name: zookeper-pod
      labels:
        app: zookeper
    spec:
      containers:
      - name: zookeper
        image: confluentinc/cp-zookeeper:6.0.11
        env:
        - name: ZOOKEEPER_CLIENT_PORT
          value: "2181"
        ports:
        - containerPort: 2181
          name: zookeper
        imagePullPolicy: Never
